"use client"

import React from 'react'
import Image from 'next/image'

const AlbumWall = () => {
    return (
        <div className="absolute z-20 flex flex-col items-center gap-5 overflow-hidden">
            <div className="flex items-center gap-5">
                <Image
                    src="/images/albums/19_and_dangerous.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/my_21st_century_symphony.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/believe.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/onepointfive.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/big_ideas.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/organ_freeman.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/black_pumas.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/pink_moon.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/church.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/rattlesnake_gumbo.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
            </div>
            <div className="z-20 flex items-center gap-5">
                <Image
                    src="/images/albums/circles.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/self_care.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/elevate.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/sleeptalk.jpg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/free_nationals.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/suncity.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/good_thing.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/texas_flood.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/i_love_life_thank_you.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/the_devine_feminine.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
            </div>
            <div className="z-20 flex items-center gap-5">
                <Image
                    src="/images/albums/im_allergic_to_dogs.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/the_dip.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/juno.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/the_meters.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/love_direction.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/three_dimensions_deep.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/malibu.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/to_pimp_a_butterfly.png"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/mit_peck.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/yellow_mellow_ep.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
                <Image
                    src="/images/albums/monologue.jpeg"
                    width={150}
                    height={150}
                    alt="album"
                    className="animate-slide" 
                />
            </div>
        </div>
    );
};

export default AlbumWall;
